import { Header, Footer, PageLayout } from "@/components/layout";
import { SEO } from "@/components/SEO";

export default function TermsOfUse() {
  return (
    <PageLayout>
      <SEO
        title="Terms of Use — Aqademiq"
        description="Aqademiq Terms of Use governing access to and use of the Digital Platform made available by R13 Labs India Private Limited."
        canonical="https://aqademiq.com/terms-of-use"
        ogType="website"
        twitterCard="summary_large_image"
      />
      <Header />
      <main className="pt-28 pb-20">
        <article className="container-marketing max-w-3xl legal-prose text-foreground">
          <header className="mb-10">
            <h1 className="text-display-lg md:text-display-xl underline underline-offset-4 decoration-2">
              TERMS OF USE
            </h1>
          </header>

          <p>
            <em>This document constitutes an electronic record in terms of the Information Technology Act, 2000 ("</em><strong><em>IT Act</em></strong><em>"), and the rules, regulations and amendments thereof, as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the IT Act. This electronic record is generated by a computer system and does not require any physical or digital signatures.</em>
          </p>

          <p>
            These Terms of Use ("<strong><em>Terms</em></strong>") govern the access to and use of the Digital Platform (as defined below) made available by R13 Labs India Private Limited, operating under the brand name "Aqademiq" (hereinafter referred to as "<strong><em>Aqademiq</em></strong>", "<strong><em>We</em></strong>", "<strong><em>Us</em></strong>" or "<strong><em>Our</em></strong>").
          </p>

          <p>
            By clicking "<strong><em>I Agree</em></strong>", "<strong><em>Sign up</em></strong>", "<strong><em>Proceed</em></strong>", or any similar confirmation button, or by accessing, browsing, registering on, downloading, or otherwise using the Digital Platform, You (as defined below) expressly acknowledge that You have read and understood these Terms and consent to be bound by them. if You do not agree to these terms, You must not access or use the Digital Platform<strong><em>.</em></strong>
          </p>

          <section>
            <h2>1. <strong>DEFINITIONS AND INTERPRETATION</strong></h2>

            <h3>1.1. <strong>Definitions</strong></h3>
            <p>In these Terms, unless the context otherwise requires, the following words and expressions shall have the meanings set out below:</p>
            <p>a) " <strong>Attention Deficit / Hyperactive Disorder</strong> " means a a neurodevelopment condition recognised in medical and psychiatric literature. Any reference to <strong>Attention Deficit / Hyperactive Disorder</strong> (" <strong>ADHD</strong> ") in these Terms is descriptive only and does not constitute a diagnosis, medical opinion, or clinical claim by Aqademiq.</p>
            <p>b) " <strong>AI-Enabled Tools</strong> " means any artificial intelligence, machine-learning, algorithmic, or automated features integrated into the Digital Platform that are used to generate summaries, insights, recommendations, content, analytics, or administrative outputs for Users, and which are provided solely for informational, educational, or assistive purposes, and shall not be relied upon as professional, therapeutic, medical, psychological, legal, or financial advice, nor shall such tools independently determine User rights, eligibility, or outcomes.</p>
            <p>c) " <strong>AI-Generated Outputs</strong> " means any response, suggestion, study plan, schedule, or other content generated by Ada or any other AI-enabled feature of the Platform in response to a User's prompt or input, whether generated using models provided by Anthropic or any other third-party AI infrastructure provider engaged by Aqademiq.</p>
            <p>d) <strong>"Applicable Laws"</strong> means all laws, rules, regulations, directions, notifications, orders, and guidelines in force in India, including but not limited to the IT Act, , the IT (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011, the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, the Digital Personal Data Protection Act, 2023, and any amendments or replacements</p>
            <p>e) <strong>"Digital Platform"</strong> means the technology-enabled platform operated by Aqademiq, comprising the Aqademiq web application accessible at Aqademiq — AI Study Planner for Students Who Procrastinate | ADHD-Friendly and mobile application, including the "IOS" and "Android" applications, and any related interfaces through which the Services are made available,.</p>
            <p>f) <strong>"Information"</strong> means any data, content, materials, inputs, or outputs, including study plans, syllabi, notes, schedules, goals, text, messages, and other information that is: (i) provided by a User or on the User's behalf (including by a parent or legal guardian) to Aqademiq; (ii) generated, processed, or displayed through the Digital Platform (including Ada).</p>
            <p>g) <strong>"Intellectual Property / Intellectual Property Rights"</strong> means all intellectual property rights of any kind, whether registered or unregistered, anywhere in the world, including copyrights, moral rights, trademarks, service marks, trade names, trade secrets, know-how, confidential information, database rights, software rights, and all similar or equivalent rights, together with all applications, renewals, and extensions thereof.</p>
            <p>h) <strong>"Guest Mode"</strong> means the limited, unregistered mode in which a User may explore certain features of the Platform prior to creating an account or providing Personal Data.</p>
            <p>i) <strong>"Platform IP"</strong> means all Intellectual Property subsisting in or relating to the Digital Platform and Aqademiq's business, including the software, source code, user interface, design elements, the sound engine, content libraries, prompts, workflows, datasets, documentation, analytics, and all improvements, enhancements, and derivative works thereto.</p>
            <p>j) <strong>"Privacy Policy"</strong> means the privacy policy issued by Aqademiq on the Digital Platform, as amended from time to time. For the purposes of these Terms, expressions relating to data protection, including "Personal Data", "Processing", "Consent", "Data Principal", "Data Fiduciary", and "Data Processor", shall have the meanings assigned to them under the Privacy Policy and Applicable Laws.</p>
            <p>k) <strong>"Prohibited Uses"</strong> means any use of the Digital Platform that is unlawful, unauthorised, misleading, abusive, fraudulent, or otherwise prohibited under these Terms or under Applicable Laws, as further described in Section 8.</p>
            <p>l) <strong>"Services"</strong> means the academic planning, schedule management, task tracking, and grade-tracking functionality offered through the Platform, together with the AI-enabled features provided through Ada, which operate as supplementary tools to assist Users and do not independently determine any User's academic outcomes, rights, or eligibility.</p>
            <p>m) <strong>"Third-Party Services"</strong> means any third-party technologies, large language models, application programming interfaces, cloud infrastructure, application stores, payment processors, websites, applications, tools, or resources that are integrated into, connected to, or accessible through the Digital Platform but that are not owned or controlled by Aqademiq.</p>
            <p>n) <strong>"User / You / Your"</strong> means any individual who registers for, or otherwise accesses or interacts with the Platform or Services, including Users who access the Platform in Guest Mode.</p>

            <h3>1.2. <strong>Interpretation</strong></h3>
            <p>Unless the context otherwise requires:</p>
            <p>a) words importing the singular include the plural and vice versa;</p>
            <p>b) headings are for convenience only and shall not affect interpretation;</p>
            <p>c) the words "include", "includes", and "including" shall be construed as being followed by "without limitation";</p>
            <p>d) references to a "Section" refer to Sections of these Terms; and</p>
            <p>e) any reference to a statute or law includes amendments, replacements, and re-enactments thereof.</p>

            <h3>1.3. <strong>Changes to Terms</strong></h3>
            <p>a) We reserve the right to modify, update, or revise these Terms from time to time. Any such changes shall become effective upon being posted on the Digital Platform, unless a later effective date is expressly stated.</p>
            <p>b) Where required by Applicable Law, We will provide reasonable notice of material changes to these Terms through the Digital Platform or through push notifications, or such other channels as We may reasonably determine. Your continued access to or use of the Digital Platform after the effective date of any changes shall constitute Your acceptance of the revised Terms. If You do not agree to the modified Terms, You must discontinue use of the Digital Platform.</p>
            <p>c) You are encouraged to review these Terms periodically, and in any event as and when notified by Us, to remain informed of any updates. The most current version of these Terms, as made available on the Platform, shall supersede all prior versions.</p>
            <p>d) Any changes that result in the collection, use, or Processing of additional Personal Data shall be governed by the Privacy Policy.</p>
          </section>

          <section>
            <h2>2. <strong>CHANGES TO THE DIGITAL PLATFORM AND SERVICES</strong></h2>
            <p>2.1. Aqademiq may, at its sole discretion, update, modify, enhance, suspend, or discontinue any feature, functionality, interface, content, or component of the Digital Platform at any time, for purposes including, but not limited to, system maintenance, security enhancement, regulatory or legal compliance, performance improvement, correction of errors, or user-experience optimisation.</p>
            <p>2.2. Where such changes materially affect paid Services, Aqademiq shall use commercially reasonable efforts to provide prior notice, unless the change is required on an urgent basis. The User acknowledges that the Digital Platform is continuously evolving, and Aqademiq shall not be liable for any modification, suspension, or discontinuation of any part of the Digital Platform or Services, except as required under Applicable Laws or the applicable refund policy.</p>
          </section>

          <section>
            <h2>3. <strong>ELIGIBILITY, AGE VERIFICATION AND PARENTAL CONSENT</strong></h2>
            <p>3.1. Use of the Digital Platform and the Services is available to individuals who are at least (18) eighteen years at least eighteen (18) years of age and who are competent to enter into a binding contract under Applicable Laws, The Digital Platform under Applicable Laws. The Digital Platform is not intended for, and must not be accessed or used by, any individual under the age of eighteen (18).</p>
            <p>3.2. 3.2 By accessing or using the Digital Platform, the User represents and warrants that they are at least eighteen (18) years of age and that all information provided regarding their age and eligibility is true, accurate and complete.</p>
            <p>3.3. 3.3 Aqademiq does not undertake any independent or advance verification of a User's age or eligibility and the shall not be responsible eligibility and shall not be responsible or liable in any manner where a User falsifies, misrepresents, or provides inaccurate information regarding their age. Responsibility and liability for any such false or inaccurate declaration rests solely with the User and/or the person providing such consent, and not with us. Aqademiq shall not be responsible or liable in any manner where a User falsifies, misrepresents, or provides inaccurate information regarding their age or the existence of parental or guardian consent. Responsibility and liability for any such false or inaccurate declaration rests solely with the User and/or the person providing such consent, and not with us.</p>
            <p>3.4. Aqademiq reserves the right to verify eligibility and to refuse, restrict, suspend, or terminate access to the Digital Platform where it reasonably believes that a User does not meet the eligibility or consent requirements, or where required under Applicable Laws.</p>
            <p>3.5. If You access or use the Digital Platform on behalf of any other person (including a Child or dependent), You represent and warrant that You have the legal authority to bind such person to these Terms, and You agree to be responsible for, and to indemnify Aqademiq against, any loss, harm, or liability arising from such access or use.</p>
          </section>

          <section>
            <h2>4. <strong>ACCOUNT REGISTRATION AND SECURITY</strong></h2>
            <p>4.1. To access and use the Digital Platform, You may be required to create an account by completing the registration process, which may require You to provide certain Information (including Personal Data such as name, email address, age, and university or educational details). By registering, You acknowledge that Your account and any Information associated with it will be used strictly in accordance with these Terms and the Privacy Policy.</p>
            <p>4.2. You represent and warrant that all Information provided by You is true, accurate, current, and complete at the time of submission, and You shall promptly update such Information to ensure its continued accuracy. You acknowledge that providing false, inaccurate, incomplete, or misleading Information may result in suspension or termination of access to the Digital Platform, and that we shall not be responsible or liable for any consequences resulting therefrom.</p>
            <p>4.3. You are responsible for maintaining the confidentiality and security of Your account credentials, including Your username, password, registered devices, and access tokens. You agree not to share Your account or login credentials with, or otherwise make Your account available to, any other person, and You shall not sell, transfer, distribute, or assign Your account to any other person.</p>
            <p>4.4. You shall be solely responsible for all activities that occur under Your account. To the maximum extent permitted by Applicable Laws, Aqademiq disclaims any liability for losses arising from unauthorised access to Your account resulting from Your failure to maintain adequate security of Your credentials, device, or access controls.</p>
            <p>4.5. If You believe, or have reason to believe, that the security of Your account has been compromised, or that any unauthorised activity has occurred in relation to Your account, You shall immediately notify Us using the contact details provided on the Digital Platform. Upon detection of any actual or suspected security breach, unauthorised access, account sharing, or misuse, Aqademiq may, without prior notice and without liability, require You to change Your credentials, or suspend or terminate Your account (temporarily or permanently).</p>
          </section>

          <section>
            <h2>5. <strong>NATURE OF SERVICES AND NO MEDICAL CLAIMS</strong></h2>
            <p>5.1. The Digital Platform is a study-focused and productivity application that offers an ADHD-friendly interface design and a procrastination-psychology-based sound engine, together with AI-generated study plans and related tools, intended to assist Users in organising and managing their study and learning activities.</p>
            <p>5.2. The Services are positioned as wellness- and productivity-oriented technology only. The Digital Platform, its ADHD-friendly design, the sound engine, and all outputs of the AI-Enabled Tools are not clinically validated, are not medical devices, and do not constitute or provide medical, psychiatric, psychological, therapeutic, diagnostic, or clinical services. Aqademiq does not diagnose, treat, cure, mitigate, or prevent ADHD or any other medical, psychological, or neurological condition or disorder, and makes no representation or claim to that effect.</p>
            <p>5.3. The design, sound engine, and features of the Digital Platform are based on research in psychology and productivity but have not been subject to clinical validation or regulatory approval. Nothing on the Digital Platform should be construed as a substitute for professional medical advice, diagnosis, or treatment. Users are advised to consult a qualified healthcare professional in relation to any medical or psychological condition, and never to disregard professional advice or delay seeking it on account of anything accessed through the Digital Platform.</p>
            <p>5.4. Study plans and other outputs generated through the Services are provided for informational and educational purposes only. Aqademiq does not warrant or guarantee the accuracy, completeness, suitability, or effectiveness of any study plan or output, or any particular academic, learning, or performance outcome, and the ultimate responsibility for reviewing, evaluating, and acting upon any such output rests with the User.</p>
          </section>

          <section>
            <h2>6. <strong>USE OF ARTIFICIAL INTELLIGENCE</strong></h2>
            <p>6.1. The AI-Enabled Tools made available on the Digital Platform, including Ada operate as a custom interface, wrapper, and prompt layer built over third-party large language models and other Third-Party Services (which may include models provided by third parties such as Anthropic and OpenAI). Aqademiq does not itself develop, train, or own the underlying large language models and adds custom instructions, prompts, and safeguards on top of such third-party technologies.</p>
            <p>6.2. The User acknowledges and agrees that Information manually provided by the User (including study plans, syllabi, and other inputs) is not used by Aqademiq to train general-purpose artificial intelligence models. The use of Personal Data in connection with the AI-Enabled Tools shall be governed by the Privacy Policy and Applicable Laws.</p>
            <p>6.3. Because the AI-Enabled Tools rely on third-party models, their outputs may be variable, incomplete, inaccurate, or otherwise erroneous, and may include content commonly described as "hallucinations". Aqademiq does not control such third-party systems and shall not be responsible for their performance, availability, or outputs. Outputs are informational and assistive only and are subject to the disclaimers and limitations set out in Section 14.</p>
            <p>6.4. The AI-Enabled Tools do not deploy autonomous or decision-making systems that independently determine any User's rights, eligibility, or other legally significant outcomes. The User agrees that AI-generated outputs require independent assessment and human oversight, that such outputs must not be blindly relied upon, and that the User shall exercise their own judgement and, where appropriate, seek guidance from qualified independent professionals before acting on any AI-generated output.</p>
            <p>6.5. As Aquademiq engages with Third-Party Service Providers, the User acknowledges that such Third Party Service Providers are shall take reasonable steps to ensure that such providers are subject to their own applicable terms, safeguards, and confidentiality and data-protection obligations.</p>
          </section>

          <section>
            <h2>7. <strong>USER-GENERATED CONTENT AND UPLOADS</strong></h2>
            <p>7.1. The User retains ownership of the Information and content that the User submits or uploads to the Digital Platform. By submitting or uploading such content, the User grants Aqademiq a non-exclusive, worldwide, royalty-free licence to host, store, process, analyse, and display such content solely for the limited purpose of operating, providing, improving, and administering the Digital Platform and the Services, in accordance with the Privacy Policy and Applicable Laws.</p>
            <p>7.2. The User is solely responsible for the content that the User uploads or inputs and represents and warrants that the User has all necessary rights to do so and that such content does not infringe the Intellectual Property or other rights of any third party. The User is advised not to upload, input, or share any sensitive, confidential, proprietary, or copyrighted materials belonging to the User or to any third party.</p>
            <p>7.3. Aqademiq disclaims all liability for any User-uploaded content and for any misuse, unauthorised access, or unauthorised sharing thereof, to the maximum extent permitted under Applicable Laws. Complaints relating to copyright infringement or other objectionable content may be submitted to the Grievance Officer ("as defined in the Privacy Policy") in accordance with Section 17; however, the User acknowledges that Aqademiq's ability to remediate any resulting damage may be limited.</p>
          </section>

          <section>
            <h2>8. <strong>PROHIBITED USES AND USER CONDUCT</strong></h2>
            <p>8.1. You shall not use the Digital Platform, the Services, or any Information for any unlawful, unauthorised, or Prohibited Use. Without limitation, You shall not:</p>
            <p>a) share, sell, transfer, distribute, or otherwise make available Your account or login credentials to any other person, or use any account other than Your own;</p>
            <p>b) misuse, manipulate, or attempt to manipulate the AI-Enabled Tools, including through prompt injection or other techniques</p>
            <p>c) override, bypass, or subvert the instructions, prompts, safeguards, or intended operation of Ada or any underlying model;</p>
            <p>d) hack, attempt to hack, gain or attempt to gain unauthorised access to, probe, scan, or test the vulnerability of the Digital Platform, its systems, servers, or any Information;</p>
            <p>e) introduce any malware, virus, or other harmful component, or interfere with, disrupt, or compromise the security, integrity, or performance of the Digital Platform;</p>
            <p>f) reverse engineer, decompile, scrape, extract, or misuse any part of the Digital Platform, the sound engine, the AI-Enabled Tools, algorithms, or other Platform IP;</p>
            <p>g) impersonate any person, or submit, upload, or disseminate any false, misleading, infringing, or harmful Information or content; or</p>
            <p>h) engage in any activity that violates Applicable Laws or the rights of any third party.</p>
            <p>8.2. Aqademiq may deploy usage analytics and pattern-detection mechanisms to identify unusual usage, unusual usage spikes, or other indicators of abuse or unauthorised activity. In the event of any Prohibited Use, or where abuse is reasonably suspected, Aqademiq reserves the right to suspend or terminate Your account and access to the Digital Platform immediately and without prior notice, to restrict future access, and, in connection with premium or paid features, to impose additional controls including internet-protocol (IP) address bans and enhanced anti-fraud and security measures. Aqademiq may report conduct to the relevant authorities where required under Applicable Laws.</p>
          </section>

          <section>
            <h2>9. INTELLECTUAL PROPERTY RIGHTS</h2>
            <p>9.1. All Intellectual Property Rights, including the Platform IP, are owned by Aqademiq, its affiliates, or its licensors, and are protected under Applicable Laws. Nothing in these Terms transfers any ownership rights to the User. The User is granted only a limited, non-exclusive, non-transferable, revocable right to access and use the Services for personal, non-commercial use in accordance with these Terms.</p>
            <p>9.2. The User shall retain all ownership rights in the Information submitted or uploaded by the User through the Digital Platform. Without affecting the User's ownership of such Information, the User acknowledges and agrees that, to the fullest extent permitted under Applicable Laws, all AI-Generated Outputs, and all insights, analytics, reports, and aggregated or anonymised data generated by Aqademiq through or in connection with the Digital Platform, shall vest in and remain the property of Aqademiq. Nothing in this clause grants Aqademiq any ownership of the User's underlying Information.</p>
            <p>9.3. The User shall not copy, reproduce, distribute, modify, reverse engineer, scrape, download, republish, transmit, or commercially exploit any part of the Digital Platform or the Platform IP, including the ADHD-friendly design, the sound engine, and the AI-Enabled Tools, without the prior written consent of Aqademiq, except as expressly permitted under these Terms.</p>
          </section>

          <section>
            <h2>10. <strong>THIRD-PARTY SERVICES AND LINKS</strong></h2>
            <p>10.1. The Digital Platform integrates with, connects to, or relies upon Third-Party Services, including third-party large language models, cloud infrastructure and hosting providers, application stores, and payment processors. Aqademiq does not own or control such Third-Party Services and shall not be responsible for their content, availability, security, performance, outputs, or practices.</p>
            <p>10.2. Your use of any Third-Party Service is at Your own risk and is subject to the terms, conditions, and privacy policies of the relevant third party. The inclusion of, or integration with, any Third-Party Service does not imply endorsement by Aqademiq.</p>
            <p>10.3. The Digital Platform may contain links to third-party websites, applications, tools, or resources that are not owned or controlled by Aqademiq. Aqademiq is not responsible for the content, availability, or practices of any such third party, and access to such resources is at the User's sole risk.</p>
          </section>

          <section>
            <h2>11. <strong>DISCLAIMER OF WARRANTIES</strong></h2>
            <p>11.1. To the maximum extent permitted under Applicable Laws, and notwithstanding anything contained elsewhere in these Terms, the Digital Platform, its features, and all content made available through it, including study plans, summaries, the sound engine, and any outputs of the AI-Enabled Tools, are provided on an <strong>"as is"</strong>, <strong>"as available"</strong>, and <strong>"with all faults"</strong> basis. Aqademiq makes no warranties or representations, express or implied, regarding the accuracy, completeness, timeliness, reliability, suitability, availability, uninterrupted operation, or error-free performance of the Digital Platform or any content displayed on it.</p>
            <p>11.2. Aqademiq does not warrant that:</p>
            <p>a) the Digital Platform will meet the User's expectations, requirements, or academic, learning, or personal outcomes;</p>
            <p>b) any study plan, insight, summary, or AI-generated output will be accurate, complete, professionally validated, or fit for any particular purpose;</p>
            <p>c) the Digital Platform will be free from malware, viruses, or harmful components everytime the User accesses the Digital Platform; or</p>
            <p>d) data transmission over the internet will be secure, uninterrupted, or free from loss, corruption, or delay.</p>
            <p>11.3. No Information, recommendation, study plan, or AI-generated output on the Digital Platform shall constitute professional, medical, psychological, or other advice, warranty, assurance of outcome, or fitness for any particular purpose. The System uptime and performance of the Digital Platform will be maintained on a commercially reasonable-efforts basis but cannot be guaranteed.</p>
          </section>

          <section>
            <h2>12. <strong>LIMITATION OF LIABILITY</strong></h2>
            <p>12.1. To the maximum extent permitted under Applicable Law, Aqademiq, its directors, officers, employees, and third-party service providers shall not be liable for any direct, indirect, incidental, special, consequential, punitive, exemplary, or economic losses, including loss of data, revenue, business or academic opportunities, or goodwill, arising out of or in connection with the User's access to, use of, or inability to use the Digital Platform or Services; reliance on any User-provided, third-party, or AI-generated Information, study plan, or output; Third-Party Services or integrations; technical failures or service interruptions; or any data loss, unauthorised access, or security incident, notwithstanding the implementation of reasonable security practices in accordance with Applicable Law.</p>
            <p>12.2. Nothing in this Section shall exclude or limit any liability that cannot be excluded or limited under Applicable Laws .</p>
            <p>12.3. Subject to clause 12.2, the total aggregate liability of Aqademiq arising out of or in connection with these Terms or the use of the Digital Platform shall not exceed the greater of (i) the total amount paid by the User to Aqademiq in the three (3) months preceding the event giving rise to the claim; or (ii) ₹5,000 (Rupees Five Thousand).</p>
          </section>

          <section>
            <h2>13. <strong>INDEMNIFICATION</strong></h2>
            <p>To the maximum extent permitted under Applicable Law, You agree to defend, indemnify, and hold harmless Aqademiq and its affiliates, officers, directors, employees, agents, and third-party partners from and against any and all claims, losses, damages, liabilities, costs, and expenses (including reasonable legal fees) caused by or arising out of: (a) Your access to, use of, or misuse of the Digital Platform or the Services; (b) any breach or violation of these Terms by You; (c) any infringement or alleged infringement by You, or by any other person using Your account, of the Intellectual Property or other rights of any person, including in respect of content You upload; (d) any breach of Applicable Laws; or (e) any false, inaccurate, incomplete, or misleading Information (including any false declaration as to age or parental consent) provided by You. Aqademiq reserves the right to assume the exclusive defence and control of any matter subject to indemnification, at Your cost, and You agree to cooperate with such defence.</p>
          </section>

          <section>
            <h2>14. <strong>TERM AND TERMINATION</strong></h2>
            <p>14.1. These Terms remain valid, binding, and enforceable for as long as the User continues to access or use the Digital Platform, having perpetual and continuing effect, unless and until terminated either (a) by the User, by discontinuing all use of the Services and deleting their account; or (b) by Aqademiq, in accordance with these Terms.</p>
            <p>14.2. Aqademiq may, at its sole discretion, suspend or terminate the User's account or access to the Digital Platform or Services at any time, with or without cause or prior notice, where the User breaches these Terms, where any Information provided by the User cannot be verified, or where the User's conduct is reasonably believed to be unlawful, fraudulent, abusive, infringing, or otherwise harmful, or where such action is necessary to protect the integrity, security, or functioning of the Digital Platform or to comply with Applicable Laws.</p>
            <p>14.3. Upon termination for any reason, You must promptly cease all use of, and destroy all materials obtained from, the Digital Platform. Termination shall not affect any obligation to pay for Services already availed, or any liability that may have arisen under these Terms. Sections relating to Intellectual Property, disclaimers, limitation of liability, indemnification, and dispute resolution shall survive termination.</p>
          </section>

          <section>
            <h2>15. <strong>GOVERNING LAW AND DISPUTE RESOLUTION</strong></h2>
            <p>15.1. The User agrees to first attempt to resolve any dispute, claim, or disagreement arising out of or relating to the Digital Platform or the Services through good-faith discussions with Aqademiq by contacting the grievance or support mechanism provided on the Digital Platform.</p>
            <p>15.2. These Terms shall be governed by and construed in accordance with the laws of India.</p>
            <p>15.3. Subject to Section 20.4, the courts located at Coimbatore, India shall have exclusive jurisdiction over all disputes arising out of or relating to these Terms or the use of the Digital Platform, unless otherwise required under Applicable Laws.</p>
            <p>15.4. Notwithstanding the above, Aqademiq may, at its discretion, elect to resolve any dispute through arbitration in accordance with the Arbitration and Conciliation Act, 1996. The seat and venue of arbitration shall be <mark>Coimbatore</mark>, India, and the proceedings shall be conducted in the English language.</p>
            <p>15.5. Nothing in this Section shall restrict the right of any User to approach a consumer forum or other authority having jurisdiction under Applicable Laws.</p>
          </section>

          <section>
            <h2>16. <strong>GENERAL PROVISIONS</strong></h2>
            <p>16.1. <strong>Entire Agreement:</strong> These Terms, together with the Privacy Policy, the Supplemental Terms, and any other policies referenced herein, constitute the entire agreement between You and Aqademiq regarding the Digital Platform and supersede all prior understandings.</p>
            <p>16.2. <strong>Severability:</strong> If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions shall remain in full force and effect.</p>
            <p>16.3. <strong>No Waiver:</strong> Aqademiq's failure to enforce any right or provision of these Terms shall not be considered a waiver of such right or provision.</p>
            <p>16.4. <strong>Assignment:</strong> You may not assign or transfer these Terms or Your account without Aqademiq's prior written consent. Aqademiq may assign these Terms in connection with a merger, acquisition, or transfer of assets.</p>
            <p>16.5. <strong>Electronic Communications:</strong> When You use the Services or communicate with Aqademiq electronically, You consent to receive communications from Aqademiq electronically, whether by email, in-application notification, or notices posted on the Digital Platform, and You agree that such communications satisfy any legal requirement that they be in writing.</p>
          </section>

          <section>
            <h2>17. <strong>GRIEVANCE OFFICER</strong></h2>
            <p>In accordance with the Information Technology Act, 2000, the rules made thereunder, and the Digital Personal Data Protection Act, 2023, for any grievances, complaints, or concerns relating to the Digital Platform, the Services, user-uploaded content, or the Processing of Personal Data, Users may contact the Grievance Officer designated by Aqademiq, whose name and contact details are published on the Digital Platform and/or in the Privacy Policy:</p>
            <p><strong>Grievance Officer:</strong> Mohammed Aswath M</p>
            <p><strong>R13 Labs India Private Limited (Aqademiq)</strong></p>
            <p><strong>Email:</strong> support@aqademiq.com</p>
            <p><strong>Address:</strong> Amman Complex</p>
            <p>153 - 4 to 6 , Pankaja Mill road</p>
            <p>Ramanathapuram</p>
            <p>coimbatore 641045</p>
          </section>
        </article>
      </main>
      <Footer />
    </PageLayout>
  );
}
